### ISSUE TITLE
Add PM models

### ISSUE THREAD

**Issue by ceular** [alcachofass/devotion#19]
~~use the following command to convert to a format recognizable by VQ3~~

~~ffmpeg -i ep.tga -pix_fmt bgr24 eprgb.tga~~
forget it, this is not a file format issue

**Comment by ceular** [comment]
This line seems to be the very thing that will lead to the solution, since it displays the error message https://github.com/ceular/devotion/blob/8feb3000c6d587ded1cf92d2419db0d9c31c7f4c/ratoa_gamecode/code/cgame/cg_players.c#L786

**Comment by ceular** [comment]
Partially fixed, for now we have a flat bright shell
![image](https://user-images.githubusercontent.com/118610580/221387804-4bd6ba06-0e40-4144-a56d-5f74df744758.png)

**Comment by ceular** [comment]
cg_brightShellAlpha should be 0.0 for a closer effect

**Comment by alcachofass** [comment]
Fixed in: https://github.com/alcachofass/devotion/commit/b96fe1d4e60597fe6248b1fd9415cb925f1ed459
![shot-20230530-061650](https://github.com/alcachofass/devotion/assets/32006541/cca49f58-72f4-4356-a887-c7b16529c756)
![shot-20230529-224458](https://github.com/alcachofass/devotion/assets/32006541/87af6693-f937-4459-a352-6f6c8bfc153c)
